# Generated by Django 5.0.1 on 2024-01-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_int',
            field=models.IntegerField(default=0),
        ),
    ]
